### ISSUE TITLE
Tuotantoympäristö ei vastaa

### ISSUE THREAD

**Issue by jheijari** [nls-oskari/kartta.paikkatietoikkuna.fi#155]
https://kartta.paikkatietoikkuna.fi/ ei vastaa

**Comment by ZakarFin** [comment]
Voi olla että kestää hetken ennenkä lähtee toimimaan:
- https://www.maanmittauslaitos.fi/ajankohtaista/paikkatietoikkunassa-havaittu-hairio
- https://twitter.com/geoportal_fi/status/1397099060729991170

Pahimpaan hätään voi käyttää odotellessa https://demo-kartta.paikkatietoikkuna.fi/ vaikkei siellä ihan viimeisimpiä tasoja/julkaisuja olekaan.

**Comment by ZakarFin** [comment]
Nyt toimii taas tuotantokin 👍
